### ISSUE TITLE
the awk code is not idiomatic

### ISSUE THREAD

**Issue by drj11** [BillMills/awk-lesson#2]
The awk code isn't idiomatic and looks unusual to awk programmers (like me).

For example: `'{if (NR > 1) print $3}'` would really be better as:

`NR > 1 { print $3 }`

(there is a rough equivalence between these two forms). This changes the pedagogy a bit, but I love awk, so I'm prepared to submit a Pull Request if you're okay with that.

**Comment by katieannemills** [comment]
hmm, interesting - but I would say, and this is wading deep into 'opinion' territory, that the example as written is more _semantic_ (thanks to the explicit `if`), even if it is less _idiomatic_.

The reason I emphasize semantic code here, is that these lessons are intended for beginners - including beginners who are only just starting out scripting. I think there's value to a formulation that does what it says and says what it does. But, I'd be interested in a third opinion - @acabunoc?

**Comment by drj11** [comment]
I totally agree that the `if` form is not only more semantic, and I think it's clearer too.

But doing it this way, you're teaching people to write awk programs that will look unusual to awk programmers. They'll never learn to speak like a native. :)

The `pattern { action }` style also appears in sed (though I note that `lesson.md` doesn't cover that).

**Comment by katieannemills** [comment]
OK - a bit more context: this repo is a spin-off experiment from [our collection of intro lessons](https://github.com/mozillascience/studyGroupLessons) (we were playing with the idea of distributing lessons through bower, so needed to break this out into its own repo); this collection is intended to introduce basic concepts in programming to non-programmers. I definitely see your point, but I think the audience is going to benefit most from legibility.
