### ISSUE TITLE
Assigning to FS is problematic

### ISSUE THREAD

**Issue by drj11** [BillMills/awk-lesson#3]
In `lesson.md` after `-F` is introduced, we have:

```
{FS="[/ :]"}
```

This is problematic:
- This code is executed for every line of input, but the way it's introduced it looks like it only runs once (of course, in this case it isn't a problem, because repeating the assignment has the same effect).
- The assignment doesn't take place until after the first line is split. In this case you're not processing the first line, so you can't see the effect that this has. But if you do something like this: `awk '{FS="[/ :]"}{print $1}' /etc/passwd | sed 9q` you can see that the first line isn't split.

You don't get either of these problems when you use the `-F` option, so I would just do:

```
awk '-F[/ :]+' '{if (NR > 1) print $3}' earthquakes.dat
```

instead (the extra `+` fixes a different bug that I'm about to write up).

**Comment by katieannemills** [comment]
If I do `awk '{FS="[/ :]+"}{print $3}' earthquakes.dat`

I get

```
magnitude
01
01
01
01
01
01
02
02
02
03
03
03
```

So it looks like the first line is split - unless I'm misunderstanding something here.

**Comment by drj11** [comment]
that's why I suggested using `/etc/passwd` where you can see that it makes a difference.

**Comment by drj11** [comment]
Result of `awk '{FS="[/ :]"}{print $1}' /etc/passwd | sed 9q`:

```
root:x:0:0:root:/root:/bin/bash
daemon
bin
sys
sync
games
man
lp
mail
```

The first line does not get split at `:` (even though that matches the regular expression) because the new `FS` is not in force when the first line gets read, only after the first line gets read.

**Comment by katieannemills** [comment]
Ok, now I see it - you're right, we need something like

```
awk '-F[/ :]+' '{print $1}' filename | sed 9q
```

I'll touch this up presently - thanks!
