### ISSUE TITLE
The regular expression for FS is wrong

### ISSUE THREAD

**Issue by drj11** [BillMills/awk-lesson#4]
Short version: `FS` should be `[/ :]+` not `[/ :]`.

Long version:

On lines 4, 5, and 7 of `earthquakes.dat` `$10` will be an empty string because their is a double space in the input file. Try changing `print $3` to `print $3, $10` to illustrate this.

You don't notice this because it only happens when the depth is an integer less than 10 and in awk `"" < 10` (the empty string is mostly treated like 0).

**Comment by katieannemills** [comment]
Yes! Right you are, thanks! Will fix this when we decide what to do with #3.

**Comment by katieannemills** [comment]
thanks again for this - btw, if you'd like to make the same corrections against the [main repo](https://github.com/mozillascience/studyGroupLessons/blob/master/awk/lesson.md) (like I said, this repo was mostly just a bower test), I'd love to have a PR from you in the commit history.
